import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { HydrateClient } from "@/lib/trpc/server";

import "./globals.css";
import { TRPCProvider } from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <HydrateClient>
          <TRPCProvider>
            <ThemeProvider defaultTheme="system" storageKey="saas-theme">
              {children}
            </ThemeProvider>
          </TRPCProvider>
        </HydrateClient>
      </body>
    </html>
  );
}
