import type { Metadata } from "next";
import './globals.css';

import { SessionProvider } from 'next-auth/react';

import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <SessionProvider>
        <body suppressHydrationWarning>
          <ThemeProvider defaultTheme="system" storageKey="saas-theme">
            {children}
          </ThemeProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
