import type { Metadata } from "next";
import './globals.css';

import { ThemeProvider } from '@/components/theme-provider';

import { TRPCProvider } from './provider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body suppressHydrationWarning>
          <TRPCProvider>
            <ThemeProvider defaultTheme="system" storageKey="saas-theme">
              {children}
            </ThemeProvider>
          </TRPCProvider>
      </body>
    </html>
  );
}
